// Types matching your database structure
export interface Reservation {
  id: number;
  reservation_no: string;
  client_id: number;
  property_id: number;
  guest_name: string;
  guest_email: string;
  contact_number: string;
  contact_person_number: string;
  check_in_date: string;
  check_out_date: string;
  check_in_time: string;
  check_out_time: string;
  occupancy: number;
  base_rate: string;
  taxes: string;
  total_tariff: string;
  total_amount?: string;
  payment_mode: string;
  tariff_type: string;
  chargeable_days: number;
  admin_email: string;
  status: string;
  created_at: string;
  reservation_id: number;
  room_type: string;
  property_status: string;
  host_id: number;
  city: string;
  location: string;
  property_type: string;
  contact_person: string;
  email_id: string;
  caretaker_name: string;
  caretaker_number: string;
  master_bedroom: number;
  common_bedroom: number;
  landmark: string;
  address1: string;
  address2: string;
  address3: string;
  property_url: string;
  client_name: string;
  gst_no: string;
  street_address: string;
  street_address_2: string;
  state: string;
  zip_code: string;
  updated_at: string;
  apartment_type:string;
  host_payment_mode:string;
  host_email:string;

}